BindingPropertyValues ={}
BindingPropertyValues['bBcc'] = ["<boolean>"]
BindingPropertyValues['PageNum'] = ['<Int-0-6>']
BindingPropertyValues['nFace'] =  ['<Int-0-3>']
BindingPropertyValues['nNonPrint'] =  ['<Int-0-3>']
BindingPropertyValues['nRow'] =  ['<Int-0-4>']
BindingPropertyValues['cLabel'] = ['<String>']
BindingPropertyValues['Annotation_author'] =['<String>']
BindingPropertyValues['cLegalAttest'] = ['<String>']
BindingPropertyValues['cTooltext'] = ['<String>']
BindingPropertyValues['cPath'] = ['<String>']
BindingPropertyValues['cName'] = ['<String>']
BindingPropertyValues['nMilliseconds'] = ['<Int-0-4000>']
BindingPropertyValues['oFunc'] = ['<Func>']
BindingPropertyValues['aFields'] = ["<Field_Ar>"]
BindingPropertyValues['Rotation'] = ['90','180','270','0']
BindingPropertyValues['SortBy'] = ['ANSB_None', 'ANSB_Page', 'ANSB_Author', 'ANSB_ModDate', 'ANSB_Type']
BindingPropertyValues['FilterBy'] = ['ANFB_ShouldNone', 'ANFB_ShouldPrint', 'ANFB_ShouldView', 'ANFB_ShouldEdit', 'ANFB_ShouldAppearInPanel', 'ANFB_ShouldSummarize', 'ANFB_ShouldExport']
BindingPropertyValues['BorderStyle'] = ['border.solid', 'border.dashed', 'border.dashed', 'border.dashed', 'border.dashed', 'border.beveled', 'border.inset', 'border.underline']

BindingStrPropertyValues = {}
BindingStrPropertyValues['FieldType'] = ["text","button","combobox","listbox", "checkbox","radiobutton","signature"]
BindingStrPropertyValues['Alignment'] =["left", "right", "center", ]
BindingStrPropertyValues['FontFamily'] = ["symbol", "serif", "sans-serif", "cursive", "monospace", "fantasy"]
BindingStrPropertyValues['FontStretch'] = ["ultra-condensed", "extra-condensed", "condensed","semi-condensed", "normal", "semi-expanded", "expanded", "extra-expanded", "ultra-expanded"]
BindingStrPropertyValues['FontStyle'] = ["italic", "normal"]
BindingStrPropertyValues['MimeType'] = ["audio/wave","audio/wav","audio/x-wav","audio/x-pn-wav","audio/webm","video/webm","audio/ogg","video/ogg","application/ogg","video/x-mpg"]
BindingStrPropertyValues['ColorSpace'] = ["T","G","RGB","CMYK"]
BindingStrPropertyValues['cTrigger'] = ["MouseUp","MouseDown","MouseEnter","MouseExit","OnFocus","OnBlur","Keystroke","Validate","Calculate","Format","Format","Format","Format","Format"]
BindingStrPropertyValues['Doc_Trigger'] = ['WillClose', 'WillSave', 'DidSave', 'WillPrint', 'DidPrint']
BindingStrPropertyValues['Page_cTrigger'] = ['Open','Close']
BindingStrPropertyValues['TextFont'] = ['font.Times', 'font.TimesB', 'font.TimesI', 'font.TimesBI', 'font.Helv', 'font.HelvB', 'font.HelvI', 'font.HelvBI', 'font.Cour', 'font.CourB', 'font.CourI', 'font.CourBI', 'font.Symbol', 'font.ZapfD']
BindingStrPropertyValues['DigestMethod']= ["SHA1", "SHA256", "SHA384", "SHA512", "MD5", "RIPEMD160"]
BindingStrPropertyValues['MDP'] = ["allowNone", "default", "defaultAndComments"]
BindingStrPropertyValues['URLType'] = ["HTML","ASSP"]
BindingStrPropertyValues['LockAction'] = ["All","Include","Exclude"]
BindingStrPropertyValues['Annotation_AP'] = ["Approved", "AsIs", "Confidential", "Departmental", "Draft", "Experimental", "Expired", "Final", "ForComment", "ForPublicRelease", "NotApproved", "NotForPublicRelease", "Sold", "TopSecret"]
BindingStrPropertyValues['Annotation_arrowBegin'] = ["None", "OpenArrow", "ClosedArrow", "ROpenArrow", "RClosedArrow", "Butt", "Diamond", "Circle", "Square", "Slash"]
BindingStrPropertyValues['Annotation_arrowEnd'] = ["None", "OpenArrow", "ClosedArrow", "ROpenArrow", "RClosedArrow", "Butt", "Diamond", "Circle", "Square", "Slash"]
BindingStrPropertyValues['Annotation_attachIcon'] = ["Paperclip", "PushPin", "Graph", "Tag"]
BindingStrPropertyValues['Annotation_borderEffectStyle'] = ['','C']
BindingStrPropertyValues['Annotation_caretSymbol'] = ['P','S','']
BindingStrPropertyValues['Annotation_inReplyTo'] = ['<AnnotationName>','<AnnotationName>','<AnnotationName>']
BindingStrPropertyValues['Annotation_Intent'] = ['FreeTextCallout','PolygonCloud','LineArrow', 'LineDimension']
BindingStrPropertyValues['Annotation_noteIcon'] = ['Check', 'Circle', 'Comment', 'Cross', 'Help', 'Insert', 'Key', 'NewParagraph', 'Note', 'Paragraph', 'RightArrow', 'RightPointer', 'Star', 'UpArrow', 'UpLeftArrow']
BindingStrPropertyValues['Annotation_refType'] = ["R", "Group"]
BindingStrPropertyValues['Annotation_state'] = ["Marked", "Unmarked", "Accepted", "Rejected", "Cancelled", "Completed", "None"]
BindingStrPropertyValues['Annotation_stateModel'] = ["Marked", "Review"]
BindingStrPropertyValues['Annotation_style'] = ["D", "S", "D", "S", "D", "S"]
BindingStrPropertyValues['Annotation_Type'] =  ['Text', 'FreeText', 'Line', 'Square', 'Circle', 'Polygon', 'PolyLine', 'Highlight', 'Underline', 'Squiggly', 'StrikeOut', 'Stamp', 'Caret', 'Ink', 'Sound']
BindingStrPropertyValues['Packet'] = ['template' ,'datasets' ,'stylesheet' ,'xfdf' ,'sourceSet' ,'pdf' ,'config' ,'*']
BindingStrPropertyValues['LabelStyle'] = ['D', 'R', 'A','D', 'R', 'A','D', 'R', 'A']
BindingStrPropertyValues['TabOrder'] = ['rows', 'columns', 'structure']
BindingStrPropertyValues['BoxType'] = ['Art', 'Bleed', 'Crop', 'Media', 'Trim']


ListSubTypes = {}
ListSubTypes['PlayerArgs'] = {'rendition':'Rendition','doc':'Doc', 'Annot':'ScreenAnnot', 'URL':'URL', 'mimeType':'MimeType', 'settings':'MediaSettings', 'events':'EventListener','noStockEvents':'Boolean', 'fromUser':'Boolean', 'showAltText': 'Boolean', 'showEmptyAltText':'Boolean'}
ListSubTypes['Alert'] = {'type':'String', 'doc':'Doc','fromUser':'Boolean', 'error':'Error', 'errorText':'String', 'fileName':'String', 'selection': 'MediaSelection'}
ListSubTypes['Span'] = {'alignment_optional':"Alignment",'fontFamily_optional':'FontFamily','fontStretch_optional':'FontStretch', 'fontStyle_optional':'FontStyle', 'fontWeight_optional':'Number','strikethrough_optional':'Boolean', 'subscript_optional':'Boolean', 'superscript_optional':'Boolean','text':'String', 'textColor_optional':'Color', 'textSize_optional':'UnsignedInt', 'underline_optional':'Boolean'}
ListSubTypes['SeedValue'] = {'certspec':'CertificateSpecifier', 'digestMethod':'DigestMethod', 'filter':'String_Ar', 'legalAttestations': 'String_Ar', 'mdp':"MDP", 'reasons':'String_Ar','shouldAddRevInfo': 'Boolean', 'subFilter':'Boolean',  }
ListSubTypes['SigSeedValue'] = {'certspec':'CertificateSpecifier', 'digestMethod':'DigestMethod', 'filter':'String_Ar', 'legalAttestations': 'String_Ar', 'mdp':"MDP", 'reasons':'String_Ar','shouldAddRevInfo': 'Boolean', 'subFilter':'Boolean',  }
ListSubTypes['CertificateSpecifier'] = {'flags':'Number_Ar', 'issuer':'Certificate_Ar', 'keyUsage': 'Number_Ar', 'oid': 'String_Ar', 'subject':'Certificate_Ar','url':'String', 'urlType':"URLType"}
ListSubTypes['Lock'] = {'action':'LockAction', 'fields':'FieldName_Ar' }
ListSubTypes['Arg_exportAsFDFStr'] = {'bAllFields':'Boolean_optional', 'bNoPassword':'Boolean_optional', 'aFields_optional':'Field_Ar_optional', 'bFlags_optional':'Boolean', 'bAnnotations':'Boolean', 'cHRef':'cPath'}
ListSubTypes['Arg_D19326FB'] = {'arg0':'Number','arg1':'Number','arg2':'Number','arg3':'Number'}
ListSubTypes['Arg_C84ACA25'] = {'cMsg_optional':'String','bInitialValue_optional':'Boolean'}
ListSubTypes['Arg_89F31342'] = {'arg0_optional':'myValue','arg1_optional':'myValue','arg2_optional':'myValue','arg3_optional':'myValue'}
ListSubTypes['Arg_99914B93'] = {}
ListSubTypes['Arg_943E4799'] = {'arg0':'String','arg1':'Arg_5D456C42','arg2_optional':'Arg_5D456C42','arg3_optional':'Arg_5D456C42','arg4_optional':'Arg_5D456C42','arg5_optional':'Arg_5D456C42','arg6_optional':'Arg_5D456C42','arg7_optional':'Arg_5D456C42','arg8_optional':'Arg_5D456C42','arg9_optional':'Arg_5D456C42'}
ListSubTypes['Arg_3AC97ABB'] = {'arg0_optional':'String','arg1_optional':'String','arg2_optional':'String','arg3_optional':'String'}
ListSubTypes['Arg_333FA2A2'] = {'arg0_optional':'Arg_99914B93','arg1_optional':'Arg_99914B93','arg2_optional':'Arg_99914B93','arg3_optional':'Arg_99914B93'}
ListSubTypes['Arg_6532FEB7'] = {'arg0':'Number','arg1':'myValue','arg2':'myValue','arg3':'myValue'}
ListSubTypes['Arg_48BE22E2'] = {'binding_optional':'Number','duplexMode_optional':'Number','subsetFrom_optional':'Number','subsetTo_optional':'Number'}
ListSubTypes['Arg_6211426C'] = {'arg0_optional':'String'}
ListSubTypes['Arg_876E7C2F'] = {'a_optional':'Number','b_optional':'Number','c_optional':'Number','d_optional':'Number','h_optional':'Number','v_optional':'Number'}
BindingPropertyValues['myValue'] = ['<Number>','<String>','<Boolean>']
BindingPropertyValues['Arg_3F47E18F'] = ['<Boolean>','<Number>','<String>']
BindingPropertyValues['Arg_F2F7D127'] = ['<Boolean>','<Number>','<String>']
BindingPropertyValues['Arg_5DF78E32'] = ['<Boolean>','<Number>','<String>']
BindingPropertyValues['Arg_5D456C42'] = ['<String>','Arg_943E4799']
BindingPropertyValues['Arg_2F3AC73E'] = ['<String>','Arg_3AC97ABB']
BindingPropertyValues['Arg_059DC049'] = ['<String>','Arg_3AC97ABB']
BindingPropertyValues['Arg_A94C8FD7'] = ['<String>','Arg_3AC97ABB']
BindingPropertyValues['Arg_0C65A02E'] = ['<Boolean>','<Number>']
BindingPropertyValues['Arg_A4427BA5'] = ['<String>','Arg_3AC97ABB']
BindingPropertyValues['Arg_770418C3'] = ['<String>','Arg_6211426C']
BindingPropertyValues['Arg_9D84DD60'] = ['<String>','Arg_6211426C']
BindingPropertyValues['Arg_C071F9A9'] = ['<Boolean>','<Number>','<String>']
BindingPropertyValues['Arg_CEF0F5FA'] = ['<String>','Arg_3AC97ABB']
BindingPropertyValues['Arg_73241B68'] = ['<Boolean>','<Number>','<String>']
BindingPropertyValues['Arg_0BDECDAC'] = ['<Boolean>','<Number>','<String>']